name: Build Code

on: [push, pull_request]

jobs:
  initial_setup:
    runs-on: windows-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v5
      - name: Python 3.13 installation
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Testing with pytest
        run:  |
          pip install pytest
          pytest