name: Build Code

on: [push, pull_request]

jobs:
  initial_setup:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Ullasdas2004@
      DATABASE_NAME: FastAPI Social Media DB
      DATABASE_USERNAME: postgres
      TEST_DATABASE_NAME: FastAPI Social Media DB Testing
      SECRET_KEY: 09d25e094faa6ca2556c818166b7awer3rrf32fasf7784gw3tq2tdbf7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTE: 60
    runs-on: windows-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v5
      - name: Python 3.13 installation
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Testing with pytest
        run:  |
          pip install pytest
          pytest